"""ajout table html

Revision ID: 3b7f4edfef30
Revises: eca91242cf0a
Create Date: 2023-12-26 19:51:43.145014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7f4edfef30'
down_revision = 'eca91242cf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('html_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('html_code')
    # ### end Alembic commands ###
